--- #YAML:1.0
name:                VUser-Google-Api
version:             1.0.0
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Crypt::SSLeay:                 0
    Encode:                        0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
